# Clock
create_clock -period 100.000 -name clk_10mhz -waveform {0.000 50.000} [get_ports clk_10mhz]
create_clock -period 10.000 -name clk_100 [get_ports clk_100]

set_false_path -from [get_clocks zed_audio_clk_48M] -to [get_clocks clk_100]
set_false_path -from [get_clocks clk_100] -to [get_clocks zed_audio_clk_48M]

# OLED display
set_property PACKAGE_PIN U10 [get_ports oled_dc]
set_property PACKAGE_PIN U9 [get_ports oled_res]
set_property PACKAGE_PIN AB12 [get_ports oled_sclk]
set_property PACKAGE_PIN AA12 [get_ports oled_sdin]
set_property PACKAGE_PIN U11 [get_ports oled_vbat]
set_property PACKAGE_PIN U12 [get_ports oled_vdd]

# Reset
set_property PACKAGE_PIN P16 [get_ports rst]

# Voltage settings
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 13]]

set_property PACKAGE_PIN T19 [get_ports {memory[0][4]}]
set_property PACKAGE_PIN R18 [get_ports {memory[0][3]}]
set_property PACKAGE_PIN T18 [get_ports {memory[0][2]}]
set_property PACKAGE_PIN R16 [get_ports {memory[0][1]}]
set_property PACKAGE_PIN R15 [get_ports {memory[0][0]}]
set_property PACKAGE_PIN P17 [get_ports {memory[1][4]}]
set_property PACKAGE_PIN P18 [get_ports {memory[1][3]}]
set_property PACKAGE_PIN T16 [get_ports {memory[1][2]}]
set_property PACKAGE_PIN T17 [get_ports {memory[1][1]}]
set_property PACKAGE_PIN R19 [get_ports {memory[1][0]}]
set_property PACKAGE_PIN R21 [get_ports {memory[2][4]}]
set_property PACKAGE_PIN P20 [get_ports {memory[2][3]}]
set_property PACKAGE_PIN P21 [get_ports {memory[2][2]}]
set_property PACKAGE_PIN N15 [get_ports {memory[2][1]}]
set_property PACKAGE_PIN P15 [get_ports {memory[2][0]}]
set_property PACKAGE_PIN M21 [get_ports {memory[3][4]}]
set_property PACKAGE_PIN M22 [get_ports {memory[3][3]}]
set_property PACKAGE_PIN N22 [get_ports {memory[3][2]}]
set_property PACKAGE_PIN P22 [get_ports {memory[3][1]}]
set_property PACKAGE_PIN R20 [get_ports {memory[3][0]}]
set_property PACKAGE_PIN L19 [get_ports {memory[4][4]}]
set_property PACKAGE_PIN M19 [get_ports {memory[4][3]}]
set_property PACKAGE_PIN M20 [get_ports {memory[4][2]}]
set_property PACKAGE_PIN N19 [get_ports {memory[4][1]}]
set_property PACKAGE_PIN N20 [get_ports {memory[4][0]}]
set_property PACKAGE_PIN L21 [get_ports {memory[5][4]}]
set_property PACKAGE_PIN L22 [get_ports {memory[5][3]}]
set_property PACKAGE_PIN K19 [get_ports {memory[5][2]}]
set_property PACKAGE_PIN K20 [get_ports {memory[5][1]}]
set_property PACKAGE_PIN L18 [get_ports {memory[5][0]}]
set_property PACKAGE_PIN K18 [get_ports {memory[6][4]}]
set_property PACKAGE_PIN J21 [get_ports {memory[6][3]}]
set_property PACKAGE_PIN J22 [get_ports {memory[6][2]}]
set_property PACKAGE_PIN J20 [get_ports {memory[6][1]}]
set_property PACKAGE_PIN K21 [get_ports {memory[6][0]}]
set_property PACKAGE_PIN M17 [get_ports {memory[7][4]}]
set_property PACKAGE_PIN N17 [get_ports {memory[7][3]}]
set_property PACKAGE_PIN N18 [get_ports {memory[7][2]}]
set_property PACKAGE_PIN M16 [get_ports {memory[7][1]}]
set_property PACKAGE_PIN J18 [get_ports {memory[7][0]}]


set_property PACKAGE_PIN L17 [get_ports AC_ADR0]
set_property PACKAGE_PIN L16 [get_ports AC_ADR1]
set_property PACKAGE_PIN K16 [get_ports AC_GPIO0]
set_property PACKAGE_PIN K15 [get_ports AC_GPIO1]
set_property PACKAGE_PIN J15 [get_ports AC_GPIO2]
set_property PACKAGE_PIN H15 [get_ports AC_GPIO3]
set_property PACKAGE_PIN J17 [get_ports AC_MCLK]
set_property PACKAGE_PIN J16 [get_ports AC_SCK]
set_property PACKAGE_PIN G21 [get_ports AC_SDA]
set_property PACKAGE_PIN C17 [get_ports clk_100]
