# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/OWNER/Desktop/Vivado_projects/SPRO4/equalizer_may_22/equalizer_may_22.srcs/sources_1/ip/fir_compiler_7/fir_compiler_7.xci
# IP: The module: 'fir_compiler_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OWNER/Desktop/Vivado_projects/SPRO4/equalizer_may_22/equalizer_may_22.srcs/sources_1/ip/fir_compiler_7/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OWNER/Desktop/Vivado_projects/SPRO4/equalizer_may_22/equalizer_may_22.srcs/sources_1/ip/fir_compiler_7/fir_compiler_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/OWNER/Desktop/Vivado_projects/SPRO4/equalizer_may_22/equalizer_may_22.srcs/sources_1/ip/fir_compiler_7/fir_compiler_7.xci
# IP: The module: 'fir_compiler_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OWNER/Desktop/Vivado_projects/SPRO4/equalizer_may_22/equalizer_may_22.srcs/sources_1/ip/fir_compiler_7/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OWNER/Desktop/Vivado_projects/SPRO4/equalizer_may_22/equalizer_may_22.srcs/sources_1/ip/fir_compiler_7/fir_compiler_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
